version: "3.8"

services:
  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?sslmode=disable"
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMA: public

  email-service:
    build: ./email-service
    container_name: email-service
    depends_on:
      - postfix-relay

  login-service:
    build: ./login-service
    container_name: login-service
    restart: always
    environment:
      - TOKEN_SERVER_URL=${TOKEN_SERVER_URL:-https://webintern.bssb.bayern:56400/rest/zmi/token}
      - USERNAME_WEB_USER=${USERNAME_WEB_USER:-webUser}
      - PASSWORD_WEB_USER=${PASSWORD_WEB_USER:-}
      - API1_BASE_URL=${API1_BASE_URL:-https://webintern.bssb.bayern:56400/rest/zmi/api1}

  postfix-relay:
    image: boky/postfix
    container_name: postfix-relay
    restart: always
    environment:
      - RELAYHOST=relay-cluster-eu01.hornetsecurity.com
      - RELAYHOST_PORT=25 # 25 for TLS/STARTTLS (recommended)
      - SMTP_TLS_SECURITY_LEVEL=may # Enforces STARTTLS if server supports it
      - ALLOW_EMPTY_SENDER_DOMAINS=true

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "443:443" #Flutter Web HTTPS
      - "8081:8081" #Postgrest API
      - "8080:8080" #Email API
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
      - ../build/web:/web
      - ./caddy-data:/data
      - ./caddy-config:/config
    depends_on:
      - postgrest
